/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae3ee",
        "surface-dim": "#0b141c",
        "on-secondary-container": "#91f294",
        "surface-container-low": "#141c24",
        "on-primary": "#002f68",
        "secondary-container": "#007124",
        "on-secondary-fixed-variant": "#005319",
        "surface-container": "#182028",
        "on-surface": "#dae3ee",
        "surface-variant": "#2d363e",
        "on-error": "#690005",
        "tertiary": "#fabc45",
        "inverse-primary": "#005bbf",
        "surface-container-high": "#222b33",
        "on-primary-fixed-variant": "#004492",
        "on-secondary": "#00390e",
        "surface": "#0b141c",
        "primary-fixed-dim": "#acc7ff",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#422c00",
        "tertiary-fixed": "#ffdeaa",
        "surface-bright": "#313a43",
        "on-surface-variant": "#c1c6d6",
        "surface-container-highest": "#2d363e",
        "on-tertiary-fixed": "#271900",
        "background": "#0b141c",
        "on-tertiary-fixed-variant": "#5f4100",
        "inverse-on-surface": "#29313a",
        "secondary-fixed": "#97f999",
        "primary-container": "#498fff",
        "on-primary-fixed": "#001a40",
        "secondary-fixed-dim": "#7bdb80",
        "tertiary-container": "#bd8708",
        "outline": "#8b909f",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#fabc45",
        "surface-tint": "#acc7ff",
        "secondary": "#7bdb80",
        "outline-variant": "#414754",
        "on-tertiary-container": "#392600",
        "primary": "#acc7ff",
        "on-secondary-fixed": "#002106",
        "surface-container-lowest": "#060f16",
        "error-container": "#93000a",
        "on-background": "#dae3ee",
        "on-primary-container": "#00285b",
        "primary-fixed": "#d7e2ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "1rem",
        "space-lg": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "1.5rem",
        "gutter-desktop": "1rem",
        "gutter": "0.75rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "margin-desktop": "1.5rem"
      },
      fontFamily: {
        "code-md": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "code-lg": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "code-md": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.005em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "code-lg": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "12px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
